name: 'Find changed directories'
description: 'Create matrix expression to build only changed packages'
author: 'Smartly.io'
inputs:
  directory_containing:
    description: >-
      Find changes to directories containing a file with this name.

      This is mutually exclusive with the directory_levels option.
    required: false
  directory_levels:
    description: >-
      Find changes to directories nested to this level.

      e.g. "directory_levels: 1" will provide the first level (in the
      repository root) directories that contain changes, no matter how
      deeply nested the changed files are.

      This is mutually exclusive with the directory_containing option.
    required: false
  exclude:
    description: >-
      Exclude directories that match the pattern.  If overriding,
      remember to include matching /^\\.github\\/.*/.

      Exclusion is applied after discovering changes based on the
      pattern.

      This should be a regular expression pattern.
    required: false
    default: '^\.github($|\/.*)'
  force_all_on_match:
    description: >-
      Regex to monitor for changes. If any of the directories matched by
      this have changes, all directories matchable by other inputs will
      be included in the output regardless of their change status.

      Useful for monorepos where changes to shared components (like common
      libraries or CI configs) should trigger builds of all packages.
    required: false
    default: ''
outputs:
  matrix:
    description: 'Matrix to use in a downstream job'
  matrix_empty:
    description: "'true' if there are no values in the matrix"
  changed_directories:
    description: 'List of directories containing changes'
  basename:
    description: 'List of directory basenames (last path component) containing changes'
  diff_base:
    description: 'Git commit used as the base for finding pull request changes'
runs:
  using: 'node20'
  main: 'dist/index.js'
