name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: Set Node.js 20.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - name: "Install"
      run: |
        npm install
    - name: "Prettier"
      run: |
        npm run format-check
    - name: "Lint"
      run: |
        npm run lint
    - name: "Test"
      run: |
        npm run test
    - name: "build"
      run: |
        npm run build
        npm run package

  test:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        fetch-depth: 0
    - name: Set Node.js 20.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - name: "Build action for test"
      run: |
        npm install
        npm run build
        npm run package
        git clean -fXd
    - name: Run the action with levels
      uses: ./.
      with:
        directory_levels: 1
    - name: Run the action with files containing
      uses: ./.
      with:
        directory_containing: main.ts
