name: "Pull Request"

on: pull_request

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    runs-on: ubuntu-22.04
    name: "Build and release action"
    needs: [build]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure git
        uses: smartlyio/github-actions@git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@release-action-node-v1
        with:
          dry_run: true
          token: "${{ secrets.GITHUB_TOKEN }}"
