name: Build and release the action

# smartlyio/find-changes-action@v1 (under Release flow) only works on pull_request events is the reason for not using "on: push: branches: master"
on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build:
    name: Build
    # Only run when PR is closed AND merged, not when PR is just closed.
    if: github.event.pull_request.merged
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    runs-on: ubuntu-22.04
    name: "Build and release action"
    needs: [build]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure git
        uses: smartlyio/github-actions@git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@release-action-node-v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
